version: '3'
services: 
    test-laravel:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        restart: unless-stopped
        volumes:
            - .:/app
        networks:
            - sail
        ports:
            - 8000:8000
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - '3306:3306'
        networks:
            - sail
        expose:
            - '3306'
        volumes:
            - my-db:/var/lib/mysql
networks:
    sail:
        driver: bridge
volumes:
    my-db: